name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm install
      - run: npx npm-check-updates -u
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated all dependencies to the latest version
          push_options: '--force'
